<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<!DOCTYPE html>
<html>
<head>
    <title>Greeting Result</title>
</head>
<body style="font-family: Arial, sans-serif; text-align: center; margin-top: 100px;">
    <h2>Hello, <%= request.getAttribute("username") %>!</h2>
    <p>Glad to meet you. This message is generated by your servlet.</p>
    <a href="index.jsp">Go Back</a>
</body>
</html>
